name: orion_gem_dart_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

  orion_gem_nest_dart_client:
    path: ../orion_gem_nest_dart_client
    # git:
    #   url: git@github.com:joicodev/orion_gem_nest_dart_client.git
    #   ref: "develop"

  dio:
  either_dart:
  # flutter_secure_storage: ^9.2.4
  mocktail: ^1.0.4
  built_value: ^8.10.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
